// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBietKhRRNRSZTNi7jvaN7abyv2SRmXs0U',
    appId: '1:154119650435:android:df2f71cf21de097bdc2fb6',
    messagingSenderId: '154119650435',
    projectId: 'gymapp-735c9',
    databaseURL: 'https://gymapp-735c9-default-rtdb.firebaseio.com',
    storageBucket: 'gymapp-735c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8PpVz7X7w-tqNqMmk3nitWB_W7TAD3go',
    appId: '1:154119650435:ios:c4a8c439e4bd9b7adc2fb6',
    messagingSenderId: '154119650435',
    projectId: 'gymapp-735c9',
    databaseURL: 'https://gymapp-735c9-default-rtdb.firebaseio.com',
    storageBucket: 'gymapp-735c9.appspot.com',
    iosClientId:
        '154119650435-tptia717f1b5sd6gc4lupe9d43uvdvrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myGym',
  );
}
